[package]
name = "petricrab-app"
version = "0.1.1"
edition = "2024"

[dependencies]
petricrab-core = { path = "../petricrab-core" }
slotmap = "1.1"
egui_graphs = "0.31"
petgraph = "0.8"
iconflow = { version = "1.0", features = ["pack-lucide"] }
rkyv = "0.8.18"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
eframe = { version = "0.35", features = ["persistence"] }
egui-toast = "=0.21.0"
egui_dock = "0.20"
log = "0.4"
simplelog = "0.12"
log-panics = { version = "2", features = ["with-backtrace"] }
